apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
type: Opaque
data:
  GITHUB_TEAM_ID: ---
  GITHUB_OAUTH_CLIENT_ID: ---
  GITHUB_OAUTH_CLIENT_SECRET: ---
  GITHUB_OAUTH_REDIRECT_URL: ---

